enable-magisk-update = true
parallel-jobs = 1
remove-rv-integrations-checks = true

[YouTube]
app-name = "YouTube"
patches-version = "dev"
cli-version = "dev"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "eXtended"
build-mode = "module"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
github-release-dlurl = "https://github.com/AzyrRuthless/YTYTM-APK/releases/latest"
included-patches = "'MaterialYou'"
excluded-patches = "'Translations for YouTube'"
version = "20.40.45"


[Music]
app-name = "YT Music"
patches-version = "dev"
cli-version = "dev"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "eXtended"
build-mode = "module"
arch = "arm64-v8a"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
github-release-dlurl = "https://github.com/AzyrRuthless/YTYTM-APK/releases/latest"
included-patches = "'Disable music video in album'"
excluded-patches = "'SponsorBlock' 'Translations for YouTube Music'"
version = "8.40.54"
